[package]
name = "sac"
description = "A macro for constructing collections"
version = "0.2.2"
readme = "README.md"
license = "MIT"
authors = ["Kai Patrick <thiskaiguy@gmail.com>"]
repository = "https://github.com/thisKai/sac"

[dependencies]
