[package]
name = "sac"
description = "A macro for constructing collections"
version = "0.2.1"
licence = "MIT"
authors = ["Kai Patrick <thiskaiguy@gmail.com>"]
build = "build.rs"

[dependencies]

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
